// Generated list of all card image URLs for the service worker.
// Keep this in sync with the cards/ directory.
window.__TH_ALL_CARDS = [
    "/cards/Boons/Boon Base Camp.png",
    "/cards/Boons/Boon Climbing rope.png",
    "/cards/Boons/Boon Flashlight.png",
    "/cards/Boons/Boon Local Guide.png",
    "/cards/Boons/Boon Map.png",
    "/cards/Cardbacks/Boon Card Back.png",
    "/cards/Cardbacks/Number Card Back.png",
    "/cards/Number/01-blue-dagger.png",
    "/cards/Number/01-grey-skull.png",
    "/cards/Number/01-red-diamond.png",
    "/cards/Number/02-blue-dagger.png",
    "/cards/Number/02-grey-skull.png",
    "/cards/Number/02-red-diamond.png",
    "/cards/Number/03-blue-dagger.png",
    "/cards/Number/03-grey-skull.png",
    "/cards/Number/03-red-diamond.png",
    "/cards/Number/04-blue-dagger.png",
    "/cards/Number/04-grey-skull.png",
    "/cards/Number/04-red-diamond.png",
    "/cards/Number/05-blue-dagger.png",
    "/cards/Number/05-grey-skull.png",
    "/cards/Number/05-red-diamond.png",
    "/cards/Number/06-blue-dagger.png",
    "/cards/Number/06-grey-skull.png",
    "/cards/Number/06-red-diamond.png",
    "/cards/Number/07-blue-dagger.png",
    "/cards/Number/07-grey-skull.png",
    "/cards/Number/07-red-diamond.png",
    "/cards/Number/08-blue-dagger.png",
    "/cards/Number/08-grey-skull.png",
    "/cards/Number/08-red-diamond.png",
    "/cards/Number/09-blue-dagger.png",
    "/cards/Number/09-grey-skull.png",
    "/cards/Number/09-red-diamond.png",
    "/cards/Number/1 Card Skull Card Coin.png",
    "/cards/Number/10 Card Totem Coin.png",
    "/cards/Number/10-blue-dagger.png",
    "/cards/Number/10-grey-skull.png",
    "/cards/Number/10-red-diamond.png",
    "/cards/Number/2 Card Luggage Coin.png",
    "/cards/Number/3 Card Skull Card Coin.png",
    "/cards/Number/4 Card Luggage Coin.png",
    "/cards/Number/5 Card Skull Card Coin.png",
    "/cards/Number/6 Card Luggage Coin.png",
    "/cards/Number/7 Card Skull Card Coin.png",
    "/cards/Number/8 Card Luggage Coin.png",
    "/cards/Number/9 Card Skull Card Coin.png"
];
